In [223]:
import numpy as np
import re

In [224]:
#sentenses = open('sentences.txt')
#a = sentenses.readline()
#print a, type(a)
#b = a.lower()  # Смотрю, как работает функция lower()
#print b, type(b)
#c = re.split('[^a-z]', b)  # Смотрю, как работает функция re.split('[^a-z]', line)
#print c
#d = [x for x in c if x != 'n' and x != ''] # Удалил разделители строк и пустые слова
#print d
#print type(d)

# а теперь надо склеить все обратно с строку !!!!
#e = " ".join (d)
#print e

In [225]:
sentences = open('sentences.txt', 'r') 
#lower = open('sentences_lower.txt', 'w')
i = 0
dict_sent = [] # Словать для строк с нижним регистром
for line in sentences:
    if i >= 0:
        string = line.lower() # Считываю каждую строку и привожу ее к нижнему регистру
        #print string
        c = re.split('[^a-z]', string)  # Разделяю на слова re.split('[^a-z]', line)
        #print c
        d = [x for x in c if x != 'n' and x != ''] # Удалил разделители строк и пустые слова
        #print d
        e = " ".join (d) # Склеил обратно в сроку
        #lower.write(e)
        print string, e
        print
        dict_sent.append(e) # Добавляю каждую строку с нижним регистром в словарь dict_sent
    i += 1
 
sentences.close()
#lower.close()
#!cat sentences_lower.txt
#print dict_sent

in comparison to dogs, cats have not undergone major changes during the domestication process.
in comparison to dogs cats have not undergone major changes during the domestication process

as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.
as cat simply catenates streams of bytes it can be also used to concatenate binary files where it will just concatenate sequence of bytes

a common interactive use of cat for a single file is to output the content of a file to standard output.
a common interactive use of cat for a single file is to output the content of a file to standard output

cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.
cats can hear sounds too faint or too high in frequency for human ears such as those made by mice and other small animals

in one, people deliberately tamed cats in a process of artificial selectio

In [226]:
#lower = open('sentences_lower.txt', 'r')
spisok = [] # Список всех слов в файле
i = 0
for line in dict_sent:
    if i >= 0:
        spisok = spisok + re.split('[^a-z]', line.lower()) # Разбил тест на слова и склеил все в одинбольшой список list
#    i += 1

#file_lower.close()
#print spisok # если надо проверить получившийся список

In [227]:
#spisok_cut = [x for x in spisok
#              if x != 'n' and x != ''] # Удалил разделитель строк и пустые слова
# spisok_cut - список всех слов в файле без переноса строк и пробелов
#print spisok_cut

#uniq_set = list(set(spisok_cut))
# Создал набор уникальных слов, передав его встроенной функции set(). - без сохранения порядка
# Если снова понадобится реальный список, нужно аналогичным образом передать набор в функцию list()
#print len(uniq_set), uniq_set

In [228]:
uniq = [] # Список уникальных слов с сохранением порядка
keys = [] # Список ключей
k = -1
for x in spisok: 
    if x not in uniq:
        uniq.append(x) # Добавляю только уникальные слова
        k = k + 1
        keys.append(k) # Заполняю словарь keys ключами
print uniq
print keys

['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'concatenate', 'binary', 'files', 'where', 'will', 'just', 'sequence', 'a', 'common', 'interactive', 'use', 'for', 'single', 'file', 'is', 'output', 'content', 'standard', 'hear', 'sounds', 'too', 'faint', 'or', 'high', 'frequency', 'human', 'ears', 'such', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', 'one', 'people', 'deliberately', 'tamed', 'artificial', 'selection', 'they', 'were', 'useful', 'predators', 'vermin', 'domesticated', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organisms', 'that', 'possess', 'chromosomes', 'roughly', 'genes', 'domestic', 'similar', 'size', 'members', 'genus', 'felis', 'typically', 'weighing', 'between', 'kg', 'lb', 'however', 'if', 'piped', 'redirected', 'unnecessary', 'with', 'named

In [229]:
# Создание словаря с ключами: список всех уникальных слов с присвоенным каждому слову ключом
#keys_uniq = dict(zip(keys, uniq))
#print keys_uniq

In [230]:
print "Число строк = ", len(dict_sent)
print "Число уникальных слов = ", len(uniq)

Число строк =  22
Число уникальных слов =  254


In [231]:
matrix = np.zeros(shape=(len(dict_sent),len(uniq))) # Создал матрицу 22х254 print matrix
print matrix
# print uniq, (len(uniq))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [232]:
for i in range(len(dict_sent)): # Для каждой строки из dict_sent 
    string = dict_sent[i].split()
    #print string, len(string)
    
    for z in range(len(uniq)):
        matrix [i][z] = 0
        for j in range(len(string)):
            # print spisok_cut[j], uniq[z]
            if string[j] == uniq[z]:
                matrix [i][z] = matrix [i][z] + 1
                #print "строка =", i, "слово в строке =", j, string[j], "слово в uniq =", z, uniq[z], string[j] == uniq[z], matrix [i][z]
                
print matrix, type (matrix)
#print matrix [2],[0]

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]] <type 'numpy.ndarray'>


In [233]:
#Найдите косинусное расстояние от предложения в самой первой строке 
#(In comparison to dogs, cats have not undergone...) 
#до всех остальных с помощью функции scipy.spatial.distance.cosine. 
#Какие номера у двух предложений, ближайших к нему по этому расстоянию 
#(строки нумеруются с нуля)? 
#Эти два числа и будут ответами на задание. 
#Само предложение (In comparison to dogs, cats have not undergone... ) имеет индекс 0.
#import scipy.spatial.distance
#cos_matrix = []
#for i in range(len(dict_sent)):
#  cos_matrix.append(scipy.spatial.distance.cosine(word_matrix[0], word_matrix[i]))
#cos_matrix = np.array(cos_matrix) 
#print (cos_matrix)

In [234]:
import scipy.spatial.distance as ds

In [235]:
dis = [] #Сформировал массив, куда занесу косинусные расстояния

for x in range(len(matrix)):
    dis.append(ds.cosine (matrix [0], matrix [x])) 
        #Вычисление косинусных расстояний и добавление в dis

print dis
min1 = min(dis[1:len(matrix)])
print "min1:", min1, "\t", dis.index(min1)

[0.0, 0.9527544408738466, 0.8644738145642124, 0.8951715163278082, 0.7770887149698589, 0.9402385695332803, 0.7327387580875756, 0.9258750683338899, 0.8842724875284311, 0.9055088817476932, 0.8328165362273942, 0.8804771390665607, 0.8396432548525454, 0.8703592552895671, 0.8740118423302576, 0.9442721787424647, 0.8406361854220809, 0.956644501523794, 0.9442721787424647, 0.8885443574849294, 0.8427572744917122, 0.8250364469440588]
min1: 0.7327387580875756 	6


In [236]:
print "min1 = ", min1, "\t", dis.index(min1)

min2 = max(dis)
print "max = ", min2, "\t", dis.index(min2)


min1 =  0.7327387580875756 	6
max =  0.956644501523794 	17


In [237]:
for x in range(len(matrix)):
    if dis[x] > min1:
        print x, dis[x]
        if min2 > dis[x]:
            min2 = dis[x]
            print "min2 = ", dis[x], "\t", x

1 0.9527544408738466
min2 =  0.9527544408738466 	1
2 0.8644738145642124
min2 =  0.8644738145642124 	2
3 0.8951715163278082
4 0.7770887149698589
min2 =  0.7770887149698589 	4
5 0.9402385695332803
7 0.9258750683338899
8 0.8842724875284311
9 0.9055088817476932
10 0.8328165362273942
11 0.8804771390665607
12 0.8396432548525454
13 0.8703592552895671
14 0.8740118423302576
15 0.9442721787424647
16 0.8406361854220809
17 0.956644501523794
18 0.9442721787424647
19 0.8885443574849294
20 0.8427572744917122
21 0.8250364469440588


In [238]:
print "min1:", min1, "\t", dis.index(min1)
print "min2:", min2, "\t", dis.index(min2)

min1: 0.7327387580875756 	6
min2: 0.7770887149698589 	4
